networks:
  polygon_dev_network:
    name: polygon_dev_network

services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app

  mysql-db:
    image: mysql:latest
    container_name: my-mysql
    ports:
      - "3336:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init:/ranks-docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_ranks_password
      MYSQL_DATABASE: ranks_reward
      MYSQL_USER: ranks_user
      MYSQL_PASSWORD: ranks_password
    networks:
      - polygon_dev_network

volumes:
  mysqldata:

